import { StudioState } from '../engine/types';

export interface PresetTheme {
  id: string;
  name: string;
  description: string;
  color: string;
  state: Partial<StudioState>;
}

export const PRESETS: PresetTheme[] = [
  {
    id: 'indigo-flow',
    name: 'Modern Indigo',
    description: 'Clean, professional SaaS default with balanced tech aesthetic',
    color: '#6366f1',
    state: {
      h: 245,
      s: 78,
      l: 55,
      harmony: 'analogous',
      satBoost: 1.0,
      accentShift: 0,
      neutralTint: 10,
      neutralHue: 0,
      semPull: 15,
      radius: 1.0,
      spacing: 1.0,
      shadow: 1.0,
      type: 1.0,
      leading: 1.45,
    },
  },
  {
    id: 'emerald-oasis',
    name: 'Emerald Oasis',
    description: 'Fresh, eco-friendly fintech and sustainable design palette',
    color: '#10b981',
    state: {
      h: 158,
      s: 75,
      l: 45,
      harmony: 'triadic',
      satBoost: 1.05,
      accentShift: 10,
      neutralTint: 12,
      neutralHue: -15,
      semPull: 20,
      radius: 1.2,
      spacing: 1.05,
      shadow: 0.9,
      type: 1.0,
      leading: 1.5,
    },
  },
  {
    id: 'electric-violet',
    name: 'Electric Violet',
    description: 'Bold, futuristic Web3 and creative AI studio palette',
    color: '#8b5cf6',
    state: {
      h: 265,
      s: 88,
      l: 58,
      harmony: 'split',
      satBoost: 1.15,
      accentShift: -15,
      neutralTint: 18,
      neutralHue: 10,
      semPull: 30,
      radius: 1.4,
      spacing: 1.1,
      shadow: 1.4,
      type: 1.05,
      leading: 1.45,
    },
  },
  {
    id: 'crimson-energy',
    name: 'Crimson Passion',
    description: 'Punchy, high-conversion e-commerce and media palette',
    color: '#ef4444',
    state: {
      h: 355,
      s: 82,
      l: 52,
      harmony: 'complementary',
      satBoost: 1.1,
      accentShift: 5,
      neutralTint: 8,
      neutralHue: 0,
      semPull: 25,
      radius: 0.8,
      spacing: 0.95,
      shadow: 1.1,
      type: 0.98,
      leading: 1.4,
    },
  },
  {
    id: 'deep-ocean',
    name: 'Deep Sapphire',
    description: 'Deep trusted enterprise corporate banking & healthcare aesthetic',
    color: '#0284c7',
    state: {
      h: 200,
      s: 84,
      l: 46,
      harmony: 'analogous',
      satBoost: 0.95,
      accentShift: -20,
      neutralTint: 15,
      neutralHue: -10,
      semPull: 10,
      radius: 0.6,
      spacing: 1.0,
      shadow: 0.8,
      type: 1.0,
      leading: 1.48,
    },
  },
  {
    id: 'amber-glow',
    name: 'Warm Amber',
    description: 'Cozy, organic artisanal and hospitality brand system',
    color: '#f59e0b',
    state: {
      h: 38,
      s: 92,
      l: 50,
      harmony: 'tetradic',
      satBoost: 1.0,
      accentShift: 20,
      neutralTint: 14,
      neutralHue: 25,
      semPull: 35,
      radius: 1.3,
      spacing: 1.15,
      shadow: 1.2,
      type: 1.02,
      leading: 1.52,
    },
  },
  {
    id: 'nord-slate',
    name: 'Nordic Frost',
    description: 'Cool arctic tones with calm desaturated neutrals and crisp edges',
    color: '#5e81ac',
    state: {
      h: 213,
      s: 32,
      l: 52,
      harmony: 'monochrome',
      satBoost: 0.85,
      accentShift: 0,
      neutralTint: 16,
      neutralHue: -20,
      semPull: 10,
      radius: 0.5,
      spacing: 0.9,
      shadow: 0.5,
      type: 0.96,
      leading: 1.42,
    },
  },
];
